### PR TITLE
Updated questions

### PR DESCRIPTION
**Pull request by wilsonator**
Added a few questions

### CODE REVIEW

**Review by wilsonator — COMMENTED** [review]
Added a few questions for fun

**Review by wilsonator — COMMENTED** [review]
Edited final question a bit

**Review by wilsonator — COMMENTED** [review]
Edited final question a bit

**Review by wilsonator — COMMENTED** [review]
Added one more, I promise I am done :)

**Review by KranzSysdig — COMMENTED** [review]
Thank you!

**Pull request merged**
